package:
  name: spline
  version: "0.10.0.rc.1"

source:
     - path: ../../..

build:
  number: 1
  script_env:
    - CUDACXX

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - python
    - cmake =3.15
    - ninja
    - setuptools

  host:
    - python
    - numpy {{ numpy }}
    - pybind11 >=2.6.1

  run:
    - python
    - {{ pin_compatible('numpy', max_pin='x.x') }}


about:
    home: https://rieslab.de
    # dev_url: github url
    # doc_url: doc url
    # license: GPL-3.0
    # license_family: GPL
    # license_file: {{ SRC_DIR }}/LICENSE
    summary: "Cubic Spline PSF Implementation"
    description: "Tbd."
