name: build, upload and lazy test

on:
  push:
  pull_request:
  release:
    types: [edited, published]

jobs:

  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          # Windows2019 & VS 2019 supports 10.1+
          - os: ubuntu-18.04
            os_base: ubuntu
            shell: bash -l {0}

          - os: macos-10.15
            os_base: macos
            shell: bash -l {0}

          - os: windows-2019
            os_base: windows
            shell: powershell

    defaults:
      run:
        shell: ${{ matrix.shell}}

    env:
        FILENAMES: temp-filenames.txt
        ANACONDA_LABEL: dev

    steps:
      - uses: actions/checkout@v2

      - uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: python/environment.yml
          python-version: 3.7
          auto-activate-base: false
          activate-environment: spline_dev

      - name: Choose Mac OS SDK
        if: ${{ matrix.os_base == 'macos'}}
        run: sudo xcode-select --switch /Applications/Xcode_11.5.app/Contents/Developer

      - name: Install CUDA Toolkit (Windows)
        if: ${{ matrix.os_base == 'windows'}}
        uses: Jimver/cuda-toolkit@v0.1.0
        id: cuda-toolkit
        with:
          cuda: '11.2.2'

      - name: WHERE IS NVCC?
        if: ${{ matrix.os_base == 'windows'}}
        run: |
          Get-Command nvcc | Select-Object -ExpandProperty Definition

      - name: WHERE IS NVCC?
        if: ${{ matrix.os_base == 'macos' || matrix.os_base == 'ubuntu'}}
        run: |
          which nvcc

      - uses: ilammy/msvc-dev-cmd@v1

      - name: Try CMAKE directly
        run: |
          cd cpp_cuda_c
          mkdir build
          cd build
          cmake -GNinja ..
          ninja

      - name: Install conda build libraries
        run: |
          conda install conda-build conda-verify anaconda-client

      - name: Build SplinePSF (Windows)
        if: ${{ matrix.os_base == 'windows' }}
        run: |
          Set-Location -Path .\dist_tools\conda
          conda-build -c conda-forge spline
          conda-build -c conda-forge spline --output > $Env:FILENAMES
